# Generated by Django 2.2 on 2019-04-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('core', '0002_auto_20190418_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='attractions',
            field=models.ManyToManyField(to='atracoes.Atracao'),
        ),
    ]
